### ISSUE TITLE
[Feature Request] Fraction Input for Marks

### ISSUE THREAD

**Issue by AnsonCNS** [Uncle-Mitch/uqmarks#34]
Hi, first of all, thanks for your great work in bringing back a UQ grade calculator.

It would be great to add the ability to enter fractions (e.g. 9/10) instead of just percentages to the marks input section.

**Comment by Uncle-Mitch** [comment]
Thanks for the suggestion Anson. Similar functionality already exists in the weekly quiz section so I don't expect it'll be too difficult to copy over. I will try to add this hopefully soon (in SWOTVAC).

**Comment by Uncle-Mitch** [comment]
Added feature with #35
