### ISSUE TITLE
[BUG] Bug with counting cumulative marks.

### ISSUE THREAD

**Issue by rOsemium** [Uncle-Mitch/uqmarks#47]
"The assessment items do not add up to 100%." message appears for a course which has 100% marks in the table
https://www.uqmarks.com/2024S2/BIOL3222
![image](https://github.com/user-attachments/assets/20492599-416f-471d-84c4-6ba3c1981059)

**Comment by Uncle-Mitch** [comment]
Thanks for reporting this - I will investigate further and create a fix!

**Comment by Uncle-Mitch** [comment]
I've fixed the error in the code. This has been pushed to the master branch with PR #50 . The fix will be pushed to the website shortly!

Thank you once again for reporting it!
