### ISSUE TITLE
[BUG] Bar chart hover tag labels are flipped

### ISSUE THREAD

**Issue by critical-hat** [Uncle-Mitch/uqmarks#49]
![image](https://github.com/user-attachments/assets/5f58f205-cd1a-4c98-a85e-08d0d534dc06)
(https://www.uqmarks.com/analytics/courses)

The labels/values for the course and number of searches are flipped on the tag when hovering over the bar chart.

**Comment by Uncle-Mitch** [comment]
Haha whoops.
Thanks for reporting!
I've changed the code with the PR #51 - should be pushed to the live version soon!
