### ISSUE TITLE
ISSUE: Regarding Assessment with weight over 100%

### ISSUE THREAD

**Issue by JetBet71** [Uncle-Mitch/uqmarks#53]
ECON2022 - assessment weighting doesn't add to 100% as a portion of assessment (30%) consist of your 2 highest scoring problem sets of 3 15% weighting assessments.

Formula to be added to put in your three assessment marks and then returns your highest scoring marks.

**Comment by Uncle-Mitch** [comment]
Hi,
Thanks for reporting this issue.
I've manually updateed the problem sets to be 30%. 

This issue is similar to #48, I will close this issue and comment in #48 about how ECON2022 does not work either.
